export const ActionTypes = {
    FETCH_PRODUCT_REQUEST: "FETCH_PRODUCT_REQUEST",
    FETCH_PRODUCT_SUCCESS: "FETCH_PRODUCT_SUCCESS",
    FETCH_PRODUCT_FAILURE: "FETCH_PRODUCT_FAILURE",
    // PRODUCT_DETAILS: "PRODUCT_DETAILS",
};
